/**
 * Raw algorithm catalog for CFOP and its advanced sets.
 *
 * Each entry lists one or more algorithms for one case. The first algorithm is the primary one.
 * The simulator checks every algorithm in `cfop-tables.ts`. An algorithm that fails a check
 * does not enter the tables.
 */

export type AlgSet = 'F2L' | 'OLL' | 'PLL' | 'COLL' | 'WV';

export interface AlgCase {
  id: string;
  name: string;
  algs: string[];
}

const cases = (prefix: string, entries: [string, string[]][]): AlgCase[] =>
  entries.map(([name, algs]) => ({ id: `${prefix}-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`, name, algs }));

/** First-two-layers cases for the front-right slot. */
export const F2L_CASES: AlgCase[] = cases('f2l', [
  ['F2L 1', ["U R U' R'"]],
  ['F2L 2', ["y' U' R' U R"]],
  ['F2L 3', ["F' U' F"]],
  ['F2L 4', ["R U R'"]],
  ['F2L 5', ["U' R U R' U2 R U' R'"]],
  ['F2L 6', ["d R' U' R U2 R' U R"]],
  ['F2L 7', ["U' R U2 R' U2 R U' R'"]],
  ['F2L 8', ["d R' U2 R U2 R' U R"]],
  ['F2L 9', ["U' R U' R' d R' U' R"]],
  ['F2L 10', ["U' R U R' U R U R'"]],
  ['F2L 11', ["U' R U2 R' d R' U' R"]],
  ['F2L 12', ["R U' R' U R U' R' U2 R U' R'"]],
  ['F2L 13', ["d R' U R U' R' U' R"]],
  ['F2L 14', ["U' R U' R' U R U R'"]],
  ['F2L 15', ["R' D' R U' R' D R U R U' R'"]],
  ['F2L 16', ["R U' R' U d R' U' R"]],
  ['F2L 17', ["R U2 R' U' R U R'"]],
  ['F2L 18', ["y' R' U2 R U R' U' R"]],
  ['F2L 19', ["U R U2 R' U R U' R'"]],
  ['F2L 20', ["y' U' R' U2 R U' R' U R"]],
  ['F2L 21', ["R U' R' U2 R U R'"]],
  ['F2L 22', ["y' R' U R U2 R' U' R"]],
  ['F2L 23', ["U2 R2 U2 R' U' R U' R2"]],
  ['F2L 24', ["R U R' d R' U R U' R' U R"]],
  ['F2L 25', ["U' R' F R F' R U R'"]],
  ['F2L 26', ["y' R U R U R U' R' U' R'"]],
  ['F2L 27', ["R U' R' U R U' R'"]],
  ['F2L 28', ["R U R' U' F R' F' R"]],
  ['F2L 29', ["y' R' U' R U R' U' R"]],
  ['F2L 30', ["R U R' U' R U R'"]],
  ['F2L 31', ["R U' R' d R' U R"]],
  ['F2L 32', ["R U R' U' R U R' U' R U R'"]],
  ['F2L 33', ["U' R U' R' U2 R U' R'"]],
  ['F2L 34', ["U F' U F U2 F' U F"]],
  ['F2L 35', ["U' R U R' U F' U' F"]],
  ['F2L 36', ["U F' U' F U' R U R'"]],
  ['F2L 38', ["R' F R F' R U' R' U R U' R' U2 R U' R'"]],
  ['F2L 39', ["R U' R' U' R U R' U2 R U' R'"]],
  ['F2L 40', ["R U' R' U R U2 R' U R U' R'"]],
  ['F2L 41', ["r U' r' U2 r U r' R U R'"]],
]);

export const OLL_CASES: AlgCase[] = cases('oll', [
  ['OLL 1', ["R U2 R2 F R F' U2 R' F R F'"]],
  ['OLL 2', ["r U r' U2 r U2 R' U2 R U' r'"]],
  ['OLL 3', ["r' R2 U R' U r U2 r' U M'"]],
  ['OLL 4', ["M U' r U2 r' U' R U' R' M'"]],
  ['OLL 5', ["l' U2 L U L' U l"]],
  ['OLL 6', ["r U2 R' U' R U' r'"]],
  ['OLL 7', ["r U R' U R U2 r'"]],
  ['OLL 8', ["l' U' L U' L' U2 l"]],
  ['OLL 9', ["R U R' U' R' F R2 U R' U' F'"]],
  ['OLL 10', ["R U R' U R' F R F' R U2 R'"]],
  ['OLL 11', ["r U R' U R' F R F' R U2 r'"]],
  ['OLL 12', ["F R U R' U' F' U F R U R' U' F'", "M U M' U2 M U M'"]],
  ['OLL 13', ["F U R U2 R' U' R U R' F'"]],
  ['OLL 14', ["R' F R U R' F' R F U' F'"]],
  ['OLL 15', ["l' U' l L' U' L U l' U l"]],
  ['OLL 16', ["r U r' R U R' U' r U' r'"]],
  ['OLL 17', ["R U R' U R' F R F' U2 R' F R F'"]],
  ['OLL 18', ["r U R' U R U2 r2 U' R U' R' U2 r"]],
  ['OLL 19', ["r' R U R U R' U' M' R' F R F'"]],
  ['OLL 20', ["r U R' U' M2 U R U' R' U' M'"]],
  ['OLL 21', ["R U R' U R U' R' U R U2 R'"]],
  ['OLL 22', ["R U2 R2 U' R2 U' R2 U2 R"]],
  ['OLL 23', ["R2 D R' U2 R D' R' U2 R'"]],
  ['OLL 24', ["r U R' U' r' F R F'"]],
  ['OLL 25', ["F' r U R' U' r' F R"]],
  ['OLL 26', ["R U2 R' U' R U' R'"]],
  ['OLL 27', ["R U R' U R U2 R'"]],
  ['OLL 28', ["r U R' U' r' R U R U' R'"]],
  ['OLL 29', ["R U R' U' R U' R' F' U' F R U R'"]],
  ['OLL 30', ["F U R U2 R' U' R U2 R' U' F'"]],
  ['OLL 31', ["R' U' F U R U' R' F' R"]],
  ['OLL 32', ["R U B' U' R' U R B R'"]],
  ['OLL 33', ["R U R' U' R' F R F'"]],
  ['OLL 34', ["R U R2 U' R' F R U R U' F'"]],
  ['OLL 35', ["R U2 R2 F R F' R U2 R'"]],
  ['OLL 36', ["R' U' R U' R' U R U R B' R' B"]],
  ['OLL 37', ["F R' F' R U R U' R'"]],
  ['OLL 38', ["R U R' U R U' R' U' R' F R F'"]],
  ['OLL 39', ["R U R' F' U' F U R U2 R'"]],
  ['OLL 40', ["R' F R U R' U' F' U R"]],
  ['OLL 41', ["R U R' U R U2 R' F R U R' U' F'"]],
  ['OLL 42', ["R' U' R U' R' U2 R F R U R' U' F'"]],
  ['OLL 43', ["R' U' F' U F R"]],
  ['OLL 44', ["F U R U' R' F'"]],
  ['OLL 45', ["F R U R' U' F'"]],
  ['OLL 46', ["R' U' R' F R F' U R"]],
  ['OLL 47', ["F R' F' R U2 R U' R' U R U2 R'"]],
  ['OLL 48', ["F R U R' U' R U R' U' F'"]],
  ['OLL 49', ["r U' r2 U r2 U r2 U' r"]],
  ['OLL 50', ["r' U r2 U' r2 U' r2 U r'"]],
  ['OLL 51', ["F U R U' R' U R U' R' F'"]],
  ['OLL 52', ["R U R' U R U' B U' B' R'"]],
  ['OLL 53', ["l' U2 L U L' U' L U L' U l"]],
  ['OLL 54', ["r U2 R' U' R U R' U' R U' r'"]],
  ['OLL 55', ["R U2 R2 U' R U' R' U2 F R F'"]],
  ['OLL 56', ["r U r' U R U' R' U R U' R' r U' r'"]],
  ['OLL 57', ["R U R' U' M' U R U' r'"]],
]);

export const PLL_CASES: AlgCase[] = cases('pll', [
  ['Aa', ["x R' U R' D2 R U' R' D2 R2 x'"]],
  ['Ab', ["x R2 D2 R U R' D2 R U' R x'"]],
  ['E', ["x' R U' R' D R U R' D' R U R' D R U' R' D' x"]],
  ['H', ["M2 U M2 U2 M2 U M2", "R2 U2 R U2 R2 U2 R2 U2 R U2 R2"]],
  ['Ua', ["R U' R U R U R U' R' U' R2", "R U R' U R' U' R2 U' R' U R' U R"]],
  ['Ub', ["R2 U R U R' U' R' U' R' U R'", "R' U R' U' R3 U' R' U R U R2"]],
  ['Z', ["M' U M2 U M2 U M' U2 M2"]],
  ['F', ["y L R2 U R U R2 U' R' U' R2 U' R U2 L' U R'"]],
  ['Ga', ["y R2 U R' U R' U' R U' R2 D U' R' U R D'"]],
  ['Gb', ["R' U' R U D' R2 U R' U R U' R U' R2 D"]],
  ['Gc', ["y R2 U' R U' R U R' U R2 D' U R U' R' D"]],
  ['Gd', ["y2 R U R' U' D R2 U' R U' R' U R' U R2 D'"]],
  ['Ja', ["y2 L U' R' U L' U2 R U' R' U2 R"]],
  ['Jb', ["R U R' F' R U R' U' R' F R2 U' R'"]],
  ['Na', ["R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'"]],
  ['Nb', ["R' U R U' R' F' U' F R U R' F R' F' R U' R"]],
  ['Ra', ["y' R U' R' U' R U R D R' U' R D' R' U2 R'"]],
  ['Rb', ["R' U2 R U2 R' F R U R' U' R' F' R2"]],
  ['T', ["R U R' U' R' F R2 U' R' U' R U R' F'"]],
  ['V', ["y R U' R U R' D R D' R U' D R2 U R2 D' R2"]],
  ['Y', ["F R U' R' U' R U R' F' R U R' U' R' F R F'"]],
]);

export const COLL_CASES: AlgCase[] = cases('coll', [
  ['AS 1', ["y R U2 R' U' R U' R'"]],
  ['AS 2', ["y2 R2 D R' U R D' R' U R' U' R U' R'"]],
  ['AS 3', ["y2 R2 D R' U2 R D' R2 U' R U' R'"]],
  ['AS 4', ["y2 R' U' R U' R2 D' R U2 R' D R2"]],
  ['AS 5', ["y2 r' F R F' r U R'"]],
  ['AS 6', ["R U' R' U2 R U' R' U2 R' D' R U R' D R"]],
  ['S 1', ["R U R' U R U2 R'"]],
  ['S 2', ["y2 R U R' U R2 D R' U2 R D' R2"]],
  ['S 3', ["L' R U R' U' L U2 R U2 R'"]],
  ['S 4', ["y' R U R' U R U' R D R' U' R D' R2"]],
  ['S 5', ["R U' L' U R' U' L"]],
  ['S 6', ["y2 R U R' F' R U R' U R U2 R' F R U' R'"]],
  ['L 1', ["y' R U R' U R U' R' U R U' R' U R U2 R'"]],
  ['L 2', ["R' U2 R' D' R U2 R' D R2"]],
  ['L 3', ["y R U2 R D R' U2 R D' R2"]],
  ['L 4', ["y F R' F' r U R U' r'"]],
  ['L 5', ["y2 F' r U R' U' r' F R"]],
  ['L 6', ["y r U2 R2 F R F' R U2 r'"]],
  ['U 1', ["R' U' R U' R' U2 R2 U R' U R U2 R'"]],
  ['U 2', ["R' F R U' R' U' R U R' F' R U R' U' R' F R F' R"]],
  ['U 3', ["y2 R2 D R' U2 R D' R' U2 R'"]],
  ['U 4', ["F R U' R' U R U R' U R U' R' F'"]],
  ['U 5', ["R2 D' R U2 R' D R U2 R"]],
  ['U 6', ["R2 D' R U R' D R U R U' R' U' R"]],
  ['T 1', ["R U2 R' U' R U' R2 U2 R U R' U R"]],
  ['T 2', ["R' U R U2 R' L' U R U' L"]],
  ['T 3', ["y R' F' r U R U' r' F"]],
  ['T 4', ["y2 F R U R' U' R U' R' U' R U R' F'"]],
  ['T 5', ["y' r U R' U' r' F R F'"]],
  ['T 6', ["R' U R2 D r' U2 r D' R2 U' R"]],
  ['Pi 1', ["R U2 R2 U' R2 U' R2 U2 R"]],
  ['Pi 2', ["y F U R U' R' U R U' R2 F' R U R U' R'"]],
  ['Pi 3', ["R' U' F' R U R' U' R' F R2 U2 R' U2 R"]],
  ['Pi 4', ["R U R' U' R' F R2 U R' U' R U R' U' F'"]],
  ['Pi 5', ["R U' L' U R' U L U L' U L"]],
  ['Pi 6', ["R' F' U' F U' R U S' R' U R S"]],
  ['H 1', ["R U R' U R U' R' U R U2 R'"]],
  ['H 2', ["F R U' R' U R U2 R' U' R U R' U' F'"]],
  ['H 3', ["R U R' U R U L' U R' U' L"]],
  ['H 4', ["y F R U R' U' R U R' U' R U R' U' F'"]],
]);

/** Winter Variation. Every algorithm inserts the last pair and orients the last-layer corners. */
export const WV_CASES: AlgCase[] = cases('wv', [
  ['WV 1', ["U L' U2 R U R' U2 L", "U' L' U2 R U' R' U2 L", "y' U r D r' U' r D' r'", "R2 D R' U R D' R2 U R U' R'", "y U' R U2 L' U' L U2 R'", "y U R U2 L' U L U2 R'", "y2 R' F' R U R' U' R' F R2"]],
  ['WV 2', ["U R U' R'", "y U' L' U L"]],
  ['WV 3', ["R' F R U R U' R' F'", "U' L U' R U L' U R'", "y L F' L' U' L' U L F", "F R' F' U' F' U F R", "y U R' U L' U' R U' L"]],
  ['WV 4', ["U R2 D R' U' R D' R2", "y U' L2 D' L U L' D L2", "y' R2 D' R U R' D R2"]],
  ['WV 5', ["U R U' R' U R' U' R U' R' U2 R", "U R U' R' U2 R U2 R' U' R U' R'", "U2 R2 B R' U' R' U R B' U2 R'", "U R U' R' U R' U L U' R U L'", "y U' L' U L U2 L' U2 L U L' U L"]],
  ['WV 6', ["R U' R' U2 R U' R' U2 R U R'", "U' R' D' R U2 R' D R2 U' R'", "y L' U L U2 L' U L U2 L' U' L"]],
  ['WV 7', ["U R U R' U' R U' R'", "R' U' R U R U' R' U' R' U R", "y U' L' U' L U L' U L"]],
  ['WV 8', ["U2 R U' R' U R U2 R'", "y U2 M x U' L U R' L' U2 L"]],
  ['WV 9', ["U2 F' R U2 R' U2 R' F R", "U L' U2 R U L U' L' U R' U2 L", "U2 F2 R U2 R' U2 R' F2 R", "U2 L' R U R' U' R U R' U' L U' R U' R'", "y U' R U2 L' U L U2 R' U' L' U L"]],
  ['WV 10', ["R' F R2 U R' U' R U R' U' F'", "U R U R2 U' R2 U' R2 U2 R", "U2 F2 L' U L U L' U' L F2", "y U2 R U' L' U L R' U L' U L"]],
  ['WV 11', ["U2 R' U' R2 U' R2 U2 R", "y U2 L' U2 L"]],
  ['WV 12', ["R' F2 R F2 U L' U L", "U R U2 L U L' R' U2 L U L'", "y U2 L' U L U' L' U2 L"]],
  ['WV 13', ["U2 R U2 R2 U' R U' R' U2 R", "R' F R F' R' U' F' U F R", "U' F2 L' U L U' L' U' L F2", "y U' R U2 L' U' R' U R U' L U2 R'"]],
  ['WV 14', ["U2 R2 D R' U2 R D' R2", "U2 L' U R U' L U2 R'", "y U2 L U L2 U L2 U2 L'"]],
  ['WV 15', ["L' U R U' R' L", "r' F R F' M'", "L' U R U' M' x'", "y U' L' U' L2 U L2 U L2 U2 L'"]],
  ['WV 16', ["U2 L' R U R' U' L R U2 R'", "U R' D' R U R' D R2 U2 R'", "U2 R U' R' U' R' F R U R U' R' F'", "U2 M x U R' U' L R U2 R'", "y U' L' U2 R' U' R L U2 R' U' R"]],
  ['WV 17', ["R' F' R U2 R U2 R' F", "U L' U2 R U' R' U2 L U R U' R'", "U2 F2 L F2 L' U' L' U L", "y U2 L' U2 L2 U L' U L U2 L'"]],
  ['WV 18', ["U2 R U2 R'", "y U2 R U' L' U R' U2 L"]],
  ['WV 19', ["R' F2 R2 U' R' U' R U R' F2", "U2 L' U R U' R' L U' R U' R'", "y R U' L' U M' x'"]],
  ['WV 20', ["U R U' R' U' R U R' U R U2 R'", "U L' U2 L R U R' U L' U L", "y U' R U2 R' L' U' L U' R U' R'"]],
  ['WV 21', ["U R U' R2 U2 R U R' U R", "U2 R U' R D R' U' R D' R2", "y U' L2 D' L U' L' D L U2 L"]],
  ['WV 22', ["U R U R D R' U2 R D' R2", "U R2 D R' U R D' R' U2 R'", "y U' L' U L2 U L' U L U2 L'"]],
  ['WV 23', ["R2 U R' U R' U' R U R U2 R2", "U2 R U R' U' R U R D R' U R D' R2", "U2 R' U L U' R2 U L' U R'", "U2 R U' R' U L' U R U' R' L U' R U' R'", "y U2 L' U L U' L' U L U' L' U2 L"]],
  ['WV 24', ["U2 R U' R' U R U' R' U R U2 R'", "y U2 L' U2 L2 U2 L' U' L U' L'"]],
  ['WV 25', ["U2 R U2 R2 U2 R U R' U R", "U2 R U' R' U R U' R D R' U' R D' R2", "y U' L' U L2 U2 L' U' L U' L'"]],
  ['WV 26', ["U R U' R2 U' R U' R' U2 R", "U R U R' U F2 L' U L U' L' U' L F2", "y U2 L U' R' U L2 U' R U' L"]],
  ['WV 27', ["U R U R' U' R U R' U' R U' R'", "y U' L' U' L U L' U' L U L' U L"]],
]);

export const ALG_SETS: Record<AlgSet, AlgCase[]> = {
  F2L: F2L_CASES,
  OLL: OLL_CASES,
  PLL: PLL_CASES,
  COLL: COLL_CASES,
  WV: WV_CASES,
};
